-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.persona DROP CONSTRAINT IF EXISTS fk_institucion;

ALTER TABLE IF EXISTS public.persona DROP CONSTRAINT IF EXISTS fk_grado_academico;

ALTER TABLE IF EXISTS public.proyecto DROP CONSTRAINT IF EXISTS fk_grupo;

ALTER TABLE IF EXISTS public.persona_grupo DROP CONSTRAINT IF EXISTS fk_grupo;

ALTER TABLE IF EXISTS public.persona_grupo DROP CONSTRAINT IF EXISTS fk_personal;

ALTER TABLE IF EXISTS public.persona_grupo DROP CONSTRAINT IF EXISTS fk_institucion;

ALTER TABLE IF EXISTS public.persona_grupo DROP CONSTRAINT IF EXISTS fk_rol_grupo;

ALTER TABLE IF EXISTS public.equipamiento DROP CONSTRAINT IF EXISTS fk_grupo;

ALTER TABLE IF EXISTS public.revista DROP CONSTRAINT IF EXISTS fk_documentacion;

ALTER TABLE IF EXISTS public.revista DROP CONSTRAINT IF EXISTS fk_editorial;

ALTER TABLE IF EXISTS public.articulo DROP CONSTRAINT IF EXISTS fk_documentacion;

ALTER TABLE IF EXISTS public.articulo DROP CONSTRAINT IF EXISTS fk_editorial;

ALTER TABLE IF EXISTS public.libro DROP CONSTRAINT IF EXISTS fk_documentacion;

ALTER TABLE IF EXISTS public.libro DROP CONSTRAINT IF EXISTS fk_editorial;

ALTER TABLE IF EXISTS public.proyecto_libro DROP CONSTRAINT IF EXISTS fk_proyecto;

ALTER TABLE IF EXISTS public.proyecto_libro DROP CONSTRAINT IF EXISTS fk_libro;

ALTER TABLE IF EXISTS public.proyecto_revista DROP CONSTRAINT IF EXISTS fk_proyecto;

ALTER TABLE IF EXISTS public.proyecto_revista DROP CONSTRAINT IF EXISTS fk_revista;

ALTER TABLE IF EXISTS public.proyecto_articulo DROP CONSTRAINT IF EXISTS fk_proyecto;

ALTER TABLE IF EXISTS public.proyecto_articulo DROP CONSTRAINT IF EXISTS fk_articulo;

ALTER TABLE IF EXISTS public.bibliografia DROP CONSTRAINT IF EXISTS fk_grupo;

ALTER TABLE IF EXISTS public.contrato DROP CONSTRAINT IF EXISTS fk_adoptante;

ALTER TABLE IF EXISTS public.contrato DROP CONSTRAINT IF EXISTS fk_demandante;

ALTER TABLE IF EXISTS public.contrato DROP CONSTRAINT IF EXISTS fk_tipo_contrato;

ALTER TABLE IF EXISTS public.participacion DROP CONSTRAINT IF EXISTS fk_grupo;

ALTER TABLE IF EXISTS public.participacion DROP CONSTRAINT IF EXISTS fk_institucion;

ALTER TABLE IF EXISTS public.participacion DROP CONSTRAINT IF EXISTS fk_rol_participacion;

ALTER TABLE IF EXISTS public.participacion_persona DROP CONSTRAINT IF EXISTS fk_participacion;

ALTER TABLE IF EXISTS public.participacion_persona DROP CONSTRAINT IF EXISTS fk_persona;

ALTER TABLE IF EXISTS public.actividad_docente DROP CONSTRAINT IF EXISTS fk_persona;

ALTER TABLE IF EXISTS public.actividad_docente DROP CONSTRAINT IF EXISTS fk_institucion;

ALTER TABLE IF EXISTS public.distincion DROP CONSTRAINT IF EXISTS fk_proyecto;

ALTER TABLE IF EXISTS public.distincion DROP CONSTRAINT IF EXISTS fk_institucion;

ALTER TABLE IF EXISTS public.distincion DROP CONSTRAINT IF EXISTS fk_persona;

ALTER TABLE IF EXISTS public.distincion DROP CONSTRAINT IF EXISTS fk_grupo;

ALTER TABLE IF EXISTS public.erogacion DROP CONSTRAINT IF EXISTS fk_institucion;

ALTER TABLE IF EXISTS public.erogacion DROP CONSTRAINT IF EXISTS fk_tipo_erogacion;

ALTER TABLE IF EXISTS public.login_details DROP CONSTRAINT IF EXISTS fk_persona_login;


DROP TABLE IF EXISTS public.login_details;

DROP TABLE IF EXISTS public.persona;

CREATE TABLE IF NOT EXISTS public.persona
(
    id integer primary key generated always as identity,
    nombre text NOT NULL,
    apellido text NOT NULL,
    horas text NOT NULL,
    grado_academico integer NOT NULL,
    object_type text NOT NULL,
    categoria text,
    incentivo text,
    dedicacion text,
    especialidad text,
    descripcion text,
    institucion integer NOT NULL
);

DROP TABLE IF EXISTS public.login_details;

CREATE TABLE IF NOT EXISTS public.login_details
(
    id integer primary key generated always as identity,
    creted_at timestamp with time zone DEFAULT now(),
    email text primary key,
    clave text NOT NULL,
    persona_id integer NOT NULL,
    activo boolean DEFAULT true
);

DROP TABLE IF EXISTS public.proyecto;

CREATE TABLE IF NOT EXISTS public.proyecto
(
    id integer primary key generated always as identity,
    grupo integer NOT NULL,
    tipo text NOT NULL,
    codigo text NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    nombre text NOT NULL,
    descripcion text NOT NULL,
    logros text,
    dificultades text
);

DROP TABLE IF EXISTS public.grupo;

CREATE TABLE IF NOT EXISTS public.grupo
(
    id integer primary key generated always as identity,
    sigla text NOT NULL,
    nombre text NOT NULL,
    objetivos text NOT NULL,
    organigrama text,
    consejo_ejecutivo text,
    unidad_academica text
);

DROP TABLE IF EXISTS public.persona_grupo;

CREATE TABLE IF NOT EXISTS public.persona_grupo
(
    id bigint  primary key generated always as identity,
    grupo integer NOT NULL,
    persona integer NOT NULL,
    institucion integer NOT NULL,
    rol integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date
);

DROP TABLE IF EXISTS public.institucion;

CREATE TABLE IF NOT EXISTS public.institucion
(
    id integer  primary key generated always as identity,
    descripcion text NOT NULL,
    pais text
);

DROP TABLE IF EXISTS public.documentacion;

CREATE TABLE IF NOT EXISTS public.documentacion
(
    id bigint  primary key generated always as identity,
    binario bytea,
    texto text
);

DROP TABLE IF EXISTS public.equipamiento;

CREATE TABLE IF NOT EXISTS public.equipamiento
(
    id bigint  primary key generated always as identity,
    denominacion text NOT NULL,
    "fechaIngreso" date NOT NULL,
    monto money NOT NULL,
    "descripción" text,
    grupo integer NOT NULL,
    actividad bigint,
    proyecto bigint
);

DROP TABLE IF EXISTS public.rol_grupo;

CREATE TABLE IF NOT EXISTS public.rol_grupo
(
    id bigint  primary key generated always as identity,
    nombre text NOT NULL
);

DROP TABLE IF EXISTS public.revista;

CREATE TABLE IF NOT EXISTS public.revista
(
    id bigint  primary key generated always as identity,
    nombre text NOT NULL,
    issn text NOT NULL,
    fecha date NOT NULL,
    editorial integer NOT NULL,
    numero text,
    documentacion bigint NOT NULL
);

DROP TABLE IF EXISTS public.articulo;

CREATE TABLE IF NOT EXISTS public.articulo
(
    id bigint  primary key generated always as identity,
    nombre text NOT NULL,
    issn text NOT NULL,
    fecha date NOT NULL,
    editorial integer NOT NULL,
    numero text,
    pais text,
    copia text,
    documentacion bigint NOT NULL
);

DROP TABLE IF EXISTS public.libro;

CREATE TABLE IF NOT EXISTS public.libro
(
    id bigint  primary key generated always as identity,
    nombre text,
    isbn text NOT NULL,
    fecha date NOT NULL,
    editorial integer NOT NULL,
    tomo text,
    capitulo text,
    pais text,
    documentacion bigint NOT NULL

);

DROP TABLE IF EXISTS public.proyecto_libro;

CREATE TABLE IF NOT EXISTS public.proyecto_libro
(
    id bigint  primary key generated always as identity,
    proyecto bigint NOT NULL,
    libro bigint NOT NULL

);

DROP TABLE IF EXISTS public.proyecto_revista;

CREATE TABLE IF NOT EXISTS public.proyecto_revista
(
    id bigint  primary key generated always as identity,
    proyecto bigint NOT NULL,
    revista bigint NOT NULL

);

DROP TABLE IF EXISTS public.proyecto_articulo;

CREATE TABLE IF NOT EXISTS public.proyecto_articulo
(
    id bigint  primary key generated always as identity,
    proyecto bigint NOT NULL,
    articulo bigint NOT NULL

);

DROP TABLE IF EXISTS public.bibliografia;

CREATE TABLE IF NOT EXISTS public.bibliografia
(
    id integer  primary key generated always as identity,
    titulo text NOT NULL,
    autores text NOT NULL,
    editorial text NOT NULL,
    fecha date NOT NULL,
    grupo integer NOT NULL
);

DROP TABLE IF EXISTS public.contrato;

CREATE TABLE IF NOT EXISTS public.contrato
(
    id bigint primary key generated always as identity,
    adoptante integer NOT NULL,
    demandante integer,
    tipo integer NOT NULL,
    monto money NOT NULL,
    denominacion text NOT NULL,
    descripcion text
);

DROP TABLE IF EXISTS public.participacion;

CREATE TABLE IF NOT EXISTS public.participacion
(
    id bigint  primary key generated always as identity,
    grupo integer NOT NULL,
    personal integer,
    rol integer NOT NULL,
    institucion integer NOT NULL
);

DROP TABLE IF EXISTS public.participacion_persona;

CREATE TABLE IF NOT EXISTS public.participacion_persona
(
    id bigint  primary key generated always as identity,
    participacion bigint NOT NULL,
    persona integer NOT NULL

);

DROP TABLE IF EXISTS public.actividad_docente;

CREATE TABLE IF NOT EXISTS public.actividad_docente
(
    id bigint  primary key generated always as identity,
    persona integer NOT NULL,
    rol text NOT NULL,
    institucion integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date
);

DROP TABLE IF EXISTS public.distincion;

CREATE TABLE IF NOT EXISTS public.distincion
(
    id bigint  primary key generated always as identity,
    proyecto bigint NOT NULL,
    persona integer,
    grupo integer,
    fecha date NOT NULL,
    institucion integer NOT NULL

);

DROP TABLE IF EXISTS public.rol_participacion;

CREATE TABLE IF NOT EXISTS public.rol_participacion
(
    id bigint  primary key generated always as identity,
    nombre text NOT NULL

);

DROP TABLE IF EXISTS public.tipo_contrato;

CREATE TABLE IF NOT EXISTS public.tipo_contrato
(
    id integer  primary key generated always as identity,
    nombre text NOT NULL
);

DROP TABLE IF EXISTS public.tipo_erogacion;

CREATE TABLE IF NOT EXISTS public.tipo_erogacion
(
    id integer  primary key generated always as identity,
    nombre text NOT NULL
);

DROP TABLE IF EXISTS public.erogacion;

CREATE TABLE IF NOT EXISTS public.erogacion
(
    id bigint  primary key generated always as identity,
    institucion integer NOT NULL,
    tipo integer NOT NULL,
    fecha timestamp with time zone NOT NULL,
    "descripción" text,
    monto money NOT NULL,
    comprobante bytea NOT NULL
);

DROP TABLE IF EXISTS public.grado_academico;

CREATE TABLE IF NOT EXISTS public.grado_academico
(
    id bigint  primary key generated always as identity,
    nombre text NOT NULL

);

ALTER TABLE IF EXISTS public.persona
    ADD CONSTRAINT fk_institucion FOREIGN KEY (institucion)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.persona
    ADD CONSTRAINT fk_grado_academico FOREIGN KEY (grado_academico)
    REFERENCES public.grado_academico (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto
    ADD CONSTRAINT fk_grupo FOREIGN KEY (grupo)
    REFERENCES public.grupo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.persona_grupo
    ADD CONSTRAINT fk_grupo FOREIGN KEY (grupo)
    REFERENCES public.grupo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.persona_grupo
    ADD CONSTRAINT fk_personal FOREIGN KEY (persona)
    REFERENCES public.persona (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.persona_grupo
    ADD CONSTRAINT fk_institucion FOREIGN KEY (institucion)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.persona_grupo
    ADD CONSTRAINT fk_rol_grupo FOREIGN KEY (rol)
    REFERENCES public.rol_grupo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.equipamiento
    ADD CONSTRAINT fk_grupo FOREIGN KEY (grupo)
    REFERENCES public.grupo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.revista
    ADD CONSTRAINT fk_documentacion FOREIGN KEY (documentacion)
    REFERENCES public.documentacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.revista
    ADD CONSTRAINT fk_editorial FOREIGN KEY (editorial)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.articulo
    ADD CONSTRAINT fk_documentacion FOREIGN KEY (documentacion)
    REFERENCES public.documentacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.articulo
    ADD CONSTRAINT fk_editorial FOREIGN KEY (editorial)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.libro
    ADD CONSTRAINT fk_documentacion FOREIGN KEY (documentacion)
    REFERENCES public.documentacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.libro
    ADD CONSTRAINT fk_editorial FOREIGN KEY (editorial)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_libro
    ADD CONSTRAINT fk_proyecto FOREIGN KEY (proyecto)
    REFERENCES public.proyecto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_libro
    ADD CONSTRAINT fk_libro FOREIGN KEY (libro)
    REFERENCES public.libro (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_revista
    ADD CONSTRAINT fk_proyecto FOREIGN KEY (proyecto)
    REFERENCES public.proyecto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_revista
    ADD CONSTRAINT fk_revista FOREIGN KEY (id)
    REFERENCES public.revista (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_articulo
    ADD CONSTRAINT fk_proyecto FOREIGN KEY (proyecto)
    REFERENCES public.proyecto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_articulo
    ADD CONSTRAINT fk_articulo FOREIGN KEY (articulo)
    REFERENCES public.articulo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.bibliografia
    ADD CONSTRAINT fk_grupo FOREIGN KEY (grupo)
    REFERENCES public.grupo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contrato
    ADD CONSTRAINT fk_adoptante FOREIGN KEY (adoptante)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contrato
    ADD CONSTRAINT fk_demandante FOREIGN KEY (demandante)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contrato
    ADD CONSTRAINT fk_tipo_contrato FOREIGN KEY (tipo)
    REFERENCES public.tipo_contrato (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.participacion
    ADD CONSTRAINT fk_grupo FOREIGN KEY (grupo)
    REFERENCES public.grupo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.participacion
    ADD CONSTRAINT fk_institucion FOREIGN KEY (id)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.participacion
    ADD CONSTRAINT fk_rol_participacion FOREIGN KEY (rol)
    REFERENCES public.rol_participacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.participacion_persona
    ADD CONSTRAINT fk_participacion FOREIGN KEY (participacion)
    REFERENCES public.participacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.participacion_persona
    ADD CONSTRAINT fk_persona FOREIGN KEY (persona)
    REFERENCES public.persona (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.actividad_docente
    ADD CONSTRAINT fk_persona FOREIGN KEY (persona)
    REFERENCES public.persona (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.actividad_docente
    ADD CONSTRAINT fk_institucion FOREIGN KEY (institucion)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.distincion
    ADD CONSTRAINT fk_proyecto FOREIGN KEY (proyecto)
    REFERENCES public.proyecto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.distincion
    ADD CONSTRAINT fk_institucion FOREIGN KEY (institucion)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.distincion
    ADD CONSTRAINT fk_persona FOREIGN KEY (id)
    REFERENCES public.persona (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.distincion
    ADD CONSTRAINT fk_grupo FOREIGN KEY (id)
    REFERENCES public.grupo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.erogacion
    ADD CONSTRAINT fk_institucion FOREIGN KEY (institucion)
    REFERENCES public.institucion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.erogacion
    ADD CONSTRAINT fk_tipo_erogacion FOREIGN KEY (tipo)
    REFERENCES public.tipo_erogacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.login_details
    ADD CONSTRAINT fk_persona_login FOREIGN KEY (persona)
    REFERENCES public.persona (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;